### ISSUE TITLE
几个月前还可以，今天要用发现有问题

### ISSUE THREAD

**Issue by Boa-container** [wxynihao/book118-downloader#13]
开始任务后突然闪退，抓拍显示[DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.

这行字出现后马上闪退，再次打开询问是否执行，输入Y后依旧如此，是本机问题还是被max118反制了？

**Comment by bruceOrange22** [comment]
![image](https://user-images.githubusercontent.com/26430505/93177234-1720bb00-f765-11ea-9ee9-1423e2780907.png)
类似 这样

**Comment by barnett2010** [comment]
我也是， https://max.book118.com/html/2018/0206/152064377.shtm  打开就闪退了

**Comment by Globefishp** [comment]
同样的错误 作者可以修复吗

**Comment by wxynihao** [comment]
网站的显示逻辑发生了变化，我近期有空会重构一版。
因为要加班和带孩子，时间上无法保证，抱歉

**Comment by wxynihao** [comment]
看了下，比以前简单了，争取周末解决  ：）

**Comment by Globefishp** [comment]
> 看了下，比以前简单了，争取周末解决 ：）

谢谢作者!
