### ISSUE TITLE
测试有bug,不能寻找到href

### ISSUE THREAD

**Issue by renyankankan** [wxynihao/book118-downloader#3]
送使用如下预览地址，不能下载，找不到href, 麻烦帮忙看下什么问题
https://max.book118.com/html/2018/1025/5134312044001323.shtm

**Comment by jackyrong** [comment]
对，同样我也发现了这个BUG，后来看了下，好像没了img这个项：
比如：
{host=https://view56.book118.com/, viewpath=img,
 furl=o4j9ZG7fK96K7ALNwHnKKQSGvsVp16t3L2qjAOMgLa5PhA0YU4iCsE2HgBl48LfUAFdb%401PwotCUI6c%40scTEHAHgqA84BPdoELXPbed0C3k%3D,
 readlimit=RxyGYqhdBToh34X3krudLg%3D%3D, 
url=dXAxNS5ib29rMTE4LmNvbS44MFw0MDA0NjM4LTVhMzE1M2U3M2RmMGIucGRm
, ismobi=false}
这个是MAP得返回，没了img这个项目

**Comment by wxynihao** [comment]
> 送使用如下预览地址，不能下载，找不到href, 麻烦帮忙看下什么问题
> https://max.book118.com/html/2018/1025/5134312044001323.shtm

已找到原因，原因有两个
1. 某些情况获取pdf信息的url不需要跳转，具体什么情况下不跳转未知，但是可以通过正则没有获取到内容判断
2. 获取下一页的path变了，由 pdf/GetNextPage/ 修改为了 /PW/GetPage，不知道这种Path的应用范围

目前的因各种原因，时间有限，未能及时修改，见谅

**Comment by wxynihao** [comment]
> 对，同样我也发现了这个BUG，后来看了下，好像没了img这个项：
> 比如：
> {host=https://view56.book118.com/, viewpath=img,
> furl=o4j9ZG7fK96K7ALNwHnKKQSGvsVp16t3L2qjAOMgLa5PhA0YU4iCsE2HgBl48LfUAFdb%401PwotCUI6c%40scTEHAHgqA84BPdoELXPbed0C3k%3D,
> readlimit=RxyGYqhdBToh34X3krudLg%3D%3D,
> url=dXAxNS5ib29rMTE4LmNvbS44MFw0MDA0NjM4LTVhMzE1M2U3M2RmMGIucGRm
> , ismobi=false}
> 这个是MAP得返回，没了img这个项目

是的，img没有值，导致为img=null。但这个不是根本原因，正确的url的img是空字符串

**Comment by wxynihao** [comment]
> 送使用如下预览地址，不能下载，找不到href, 麻烦帮忙看下什么问题
> https://max.book118.com/html/2018/1025/5134312044001323.shtm

问题已解决，下载jar文件夹中的文件即可
