### ISSUE TITLE
页码没有按照顺序排序

### ISSUE THREAD

**Issue by singmelody** [wxynihao/book118-downloader#7]
![image](https://user-images.githubusercontent.com/2894248/68240962-cae6f380-0048-11ea-874f-ad30b1883400.png)

环境: MacOS 10.14.5 
版本:1.8.0_192
运行环境:IDEA 2019 2.3
下载图书编号: 134120889 马来西亚史

出现问题：
下载gif文件成功，生成的PDF页码乱掉，查看堆栈发现文件排序不对。堆栈如图

自己的解决办法：
`List<File> files = Arrays.asList(picFiles);`

**Comment by wxynihao** [comment]
该问题已解决 https://github.com/wxynihao/book118-downloader/releases/tag/v20200113
