### ISSUE TITLE
是不是失效了QAQ

### ISSUE THREAD

**Issue by kotonoha233** [wxynihao/book118-downloader#8]
Ver.20190629 latest: https://github.com/wxynihao/book118-downloader
添加下载任务
1. 输入文档编号, 如 3045568
2. 输入完整的文档网址, 如 https://max.book118.com/html/2012/1017/3045568.shtm
3. 输入 start, 开始下载任务
4. 输入 #, 退出程序
输入指令: 167962114
下载任务 167962114 已填加
添加下载任务
1. 输入文档编号, 如 3045568
2. 输入完整的文档网址, 如 https://max.book118.com/html/2012/1017/3045568.shtm
3. 输入 start, 开始下载任务
4. 输入 #, 退出程序
输入指令: start
待下载的文档:
167962114
下载文档： 167962114
[2019-11-25 21:40:09] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.

**Comment by wxynihao** [comment]
检查是支持的，添加后，要使用start命令开始下载
